apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: op1st-cicd
  app.kubernetes.io/component: tekton
  app.kubernetes.io/version: v1.0.0
  app.kubernetes.io/managed-by: aicoe-thoth-devops
generators:
  - ./manifests/secret-generator.yaml
